from structure_class import Structure

class Child(Structure):
    """
    Here we can decide what information and functions should be connected to the structures generated by raffle. 
    For now, nothing special
    """
    def __init__(self,atoms):
        super(Child, self).__init__(atoms)


    
